<?php

namespace Tests\ESModule\Cdc\Converter;

use App\ESModule\Cdc\Converter\MaxwellConverter;
use App\ESModule\Cdc\Dto\CdcDto;
use Tests\TestCase;

class MaxwellConverterTest extends TestCase
{
    private MaxwellConverter $maxwellConverter;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->maxwellConverter = app(MaxwellConverter::class);
    }

    public function testInsert()
    {
        $payload = '{"database":"test-db","table":"test-table","type":"insert","ts":1234,"xid":5678,"commit":true,"data":{"id":1,"name":"test-name"}}';
        $payloads = [$payload];

        $cdcDtos = $this->maxwellConverter->convertCdcPayloadsToCdcDtos($payloads);

        $this->assertEquals(1, count($cdcDtos));
        $this->assertEquals(
            new CdcDto(
                'test-db',
                'test-table',
                'insert',
                [
                    'id' => 1,
                    'name' => 'test-name',
                ],
                [],
                [],
            ),
            $cdcDtos[0],
        );
    }

    public function testDelete()
    {
        $payload = '{"database":"test-db","table":"test-table","type":"delete","ts":1234,"xid":5678,"commit":true,"data":{"id":1,"name":"test-name"}}';
        $payloads = [$payload];

        $cdcDtos = $this->maxwellConverter->convertCdcPayloadsToCdcDtos($payloads);

        $this->assertEquals(1, count($cdcDtos));
        $this->assertEquals(
            new CdcDto(
                'test-db',
                'test-table',
                'delete',
                [
                    'id' => 1,
                    'name' => 'test-name',
                ],
                [],
                [],
            ),
            $cdcDtos[0],
        );
    }

    public function testUpdate()
    {
        $payload = '{"database":"test-db","table":"test-table","type":"update","ts":1234,"xid":5678,"commit":true,"data":{"id":1,"name":"test-name"}, "old" : {"name" : "test-name-old"}}';
        $payloads = [$payload];

        $cdcDtos = $this->maxwellConverter->convertCdcPayloadsToCdcDtos($payloads);

        $this->assertEquals(1, count($cdcDtos));
        $this->assertEquals(
            new CdcDto(
                'test-db',
                'test-table',
                'update',
                [
                    'id' => 1,
                    'name' => 'test-name',
                ],
                [
                    'name',
                ],
                []
            ),
            $cdcDtos[0],
        );
    }

    public function testTwo()
    {
        $payload = '{"database":"test-db","table":"test-table","type":"insert","ts":1234,"xid":5678,"commit":true,"data":{"id":1,"name":"test-name"}, "old" : {"name" : "test-name-old"}}';
        $payload2 = '{"database":"test-db","table":"test-table","type":"update","ts":1234,"xid":5678,"commit":true,"data":{"id":1,"name":"test-name"}, "old" : {"name" : "test-name-old"}}';
        $payloads = [$payload, $payload2];

        $cdcDtos = $this->maxwellConverter->convertCdcPayloadsToCdcDtos($payloads);

        $this->assertEquals(2, count($cdcDtos));
        $this->assertEquals(
            new CdcDto(
                'test-db',
                'test-table',
                'insert',
                [
                    'id' => 1,
                    'name' => 'test-name',
                ],
                [
                    'name',
                ],
                []
            ),
            $cdcDtos[0],
        );

        $this->assertEquals(
            new CdcDto(
                'test-db',
                'test-table',
                'update',
                [
                    'id' => 1,
                    'name' => 'test-name',
                ],
                [
                    'name',
                ],
                []
            ),
            $cdcDtos[1],
        );
    }
}
